### PR TITLE
Conditions enhancements

### PR DESCRIPTION
**Pull request by dviry**
This PR includes the following enhancements:

1. additional Net47_Installed condition (just to be complete)
2. operator overloads for & (AND), | (OR) and a static NOT operator

Last point allows for some nice readable combinations (e.g. when used in ManagedActions):
```
Condition.NOT_Installed & Condition.NOT("Upgrading")

new Condition("Upgrading") | new Condition("Uninstalling")
```
PS: not sure why the previous AND, OR, NOT local scoped methods are commented out, but I've left them intact.

I hope this PR satisfies your requirements and you'll consider them useful enough to merge them into your master.

Thanks,
Leon

### CODE REVIEW

**Comment by Xaddan** [comment]
It is worth adding operator overloads for ! (NOT):
```
/// <summary>
/// Returns a new <see cref="Condition"/> adding a logical NOT before the condition.
/// </summary>
/// <param name="a">The first <see cref="Condition"/> or text</param>
/// <returns>The new NOT'ed condition.</returns>
public static Condition operator !(Condition a)
{
   return new Condition("(NOT " + a + ")");
}
```

**Comment by dviry** [comment]
Thanks Xaddan,

1. I would if that would exist (I've tried ;), but the ! overload can only return a boolean and not an object. Besides it would not look so nice with the constructor:
```
!(new Condition("Upgrading"))
```
It would be fine thought with .Create(), that's why I wrote .NOT() the same way:
```
!Condition.Create("Upgrading")  <--- cannot implement

-vs-

Condition.NOT("Upgrading")   <--- included in this PR
```

2. checking the UPGRADINGPRODUCTCODE is misleading and not the way to go about it (I've solved it [differently](https://github.com/oleg-shilo/wixsharp/issues/245#issuecomment-352925394)), so I'd rather not add it. Besides, this PR is actually about logical operators... Maybe I'll open a different PR with my suggestions regarding identifying upgrades.

Cheers,
Leon

**Comment by oleg-shilo** [comment]
> PS: not sure why the previous AND, OR, NOT local scoped methods are commented out, but I've left them intact.

They are commented because I decided not to over invest in providing API that does not improve native MSI/WiX solution. It's the "Occam's razor" principle applied to the API field. 

Authoring a **good** API is challenging. I remember, I was asked (during my interview for InfoQ) why I went further then just providing a DSL C# solution/mapper for WiX. The reason is "I wanted to fix questionable MSI/WiX programming model". This is exactly the same reason why I did not released AND, OR, NOT methods.  They don't really solve nor improve anything.

```C#
// your proposed solution
new Condition("Upgrading") | new Condition("Uninstalling")

// already existing simple solution
new Condition("Upgrading OR Uninstalling")

// existing but commented out method
new Condition("Upgrading").Or("Uninstalling")
``` 
As for me the second code line looks the most intuitive. And the first one (your solution) confuses me the most.

You see, the _condition_ expression is **boolean** by nature and you are using **bitwise** operators. These two different operator types have nothing in common and their application field is completely different: _conditional expressions_ vs. _binary bits manipulations_.  

As I see it you would have even a better solution by uncommenting (and possibly extending) those "AND, OR, NOT methods".

Please elaborate if I am missing something.

**Comment by dviry** [comment]
They are indeed coming from the C world as bitweise operators, but in C# they have a double meaning, and used to let the compiler evaluate every segment instead of the "short circuited" double operator (&& and ||) which stops as soon as one operation is true (in other words, double pipe is lazy evaluation and single pipe is greedy, within logical operator area). That's also the reason C# allows you to override those operators, and not the double ones.

Maybe the example I gave was too "simple", when there is more than just one Property it gets messy. Either way it's obviously your decision so if you want I can remove this PR and just adds the new constants for .NET.

Cheers

**Comment by oleg-shilo** [comment]
I perfectly understand your intention. I just questioned the benefits of the proposed solution.

Though... you convinced me. In fact I did it mostly by myself :) 

I sill do not like readability aspect of:  
```C#
new Condition("Upgrading") | new Condition("Uninstalling")
```

However, there is another use-case where you bitwise operators actually work very well - `Condition` constants :
```C#
new ManagedAction(CustonActions.MyAction, 
                  Return.ignore, 
                  When.After, 
                  Step.InstallFinalize, 
                  Condition.Upgrading | Condition.Installing)
```

And when combined with C#7 `using static` then it becomes actually quite nice:

```C#
using static When;
using static Step;
using static Condition;

new ManagedAction(CustonActions.MyAction, 
                  Return.ignore, After, InstallFinalize, Upgrading | Installing)
```
I will proceed with reviewing and processing the PR.

Thank you.

**Comment by dviry** [comment]
great, just wondering when are you planning to publish an updated NuGet package? Did not see any .nuspec, release scripts or any planned milestones...

Thanks

**Comment by oleg-shilo** [comment]
I have just published v1.6.1.0-HotFix NuGet package. Give it a few minutes to get indexed. 
I have also added https://github.com/oleg-shilo/wixsharp/tree/master/Source/NuGet/WixSharp

**Comment by dviry** [comment]
THANK YOU!

**Pull request merged**
