### PR TITLE
Add missing Version element to ComRegistration (Class element) and add extra validation

### PR DESCRIPTION
**Pull request by sonicbhoc**
The Class element is missing its Version attribute, which is used in non-advertised registration.

### CODE REVIEW

**Comment by sonicbhoc** [comment]
I didn't realize that the last pull request was merged in. I left it as a draft since I had a few more things to test out, but this one should be it for changes unless something else is missing.

**Comment by oleg-shilo** [comment]
Sorry it was my mistake. I interpreted PR as ready for merge.
Merging it again :)

How critical the change?
Does it need a HotFix release or we should wait till the next release in a month or so. Either way is fine

**Comment by sonicbhoc** [comment]
HotFix for sure, but make it a minor version bump since technically some of the classes in ComRegistration.cs are no longer abi-compatible; ComRegistration was pretty much completely overhauled between my last few sets of pull requests

**Comment by sonicbhoc** [comment]
Also, I wanted to thank you for working with me on this. I hope the updated ComRegistration classes help out other people too. Just let me know when you make the new package so I can hopefully finally finish this installer project I'm working on.

**Comment by sonicbhoc** [comment]
What's the status on this? Have you decided whether to release this now or later? If later, how do I roll my own version temporarily?

**Comment by oleg-shilo** [comment]
Publishing is not too time consuming.
But having too frequent releases can confuse the users. 
Considering the fact that you are still developing COM related stuff I released it as a prerelease (v1.) that will merge with the coming features in a month or so when the full version is to be released.

https://www.nuget.org/packages/WixSharp/1.18.2-pre

**Comment by sonicbhoc** [comment]
Thanks! I'll keep developing it as necessary, and releasing it as pre-release makes my life easier without potentially exposing unfinished features.

**Pull request merged**
