### PR TITLE
Rework DriverInstaller using IGenericEntity

### PR DESCRIPTION
**Pull request by Xaddan**
empty

### CODE REVIEW

**Comment by Xaddan** [comment]
I did not understand why the test failed.

**Comment by oleg-shilo** [comment]
Can you please have a look at this one. It caused the build failure: https://ci.appveyor.com/project/oleg-shilo/wixsharp/build/1.5.0.47

There is a good chance that Pull from `master` will just fix it.

**Comment by Xaddan** [comment]
image

**Comment by oleg-shilo** [comment]
It might be some merge artifact. There were a few conflicts that I had to resolve with your previous PRs. Can you please do pull and create the same fresh PR so even if it fails I know it will require minimal resolving. Thank you.

**Pull request merged**
