### PR TITLE
Update Text (Dialog title) on view title change

### PR DESCRIPTION
**Pull request by PatrickHofman**
A better proposal than pull request 1420, changing the shell title on view title change.

### CODE REVIEW

**Comment by oleg-shilo** [comment]
Agree, it is going to deliver a better dev experience.
I will split and tunnel the change to the WiX3 and WiX4 branches.
The planned next release time is in ~2 weeks from now.

**Comment by oleg-shilo** [comment]
Hey Patrick, I have repeated your solution in `wix-v4-master` branch, all good.
I can also do it for `master-wix3` it's not a problem. Though... I would prefer to preserve the fact that you are the original author of the solution. So if you are OK with it, can you please reraise this PR/change against `oleg-shilo:wix-v3-master` so I can merge it as a PR.

**Comment by PatrickHofman** [comment]
If you are fine with it, I am happy to have it in v3 also.

**Comment by oleg-shilo** [comment]
Sorry Patrick, I did not explain it well.

`master` branch is not used for PRs until WiX team completes the transition WiX3->WiX4.  Then I will merge my `wix-v4-master` to `master` and close `wix-v3-master` forever.

But until this happens I have to duplicate all PRs with shared functionality in the two branches: `wix-v4-master` and `wix-v4-master`. (see [Code-Contributions-Guideline](https://github.com/oleg-shilo/wixsharp/wiki/Code-Contributions-Guideline))

I've repeated your change in `wix-v4-master` but if I do it in `wix-v3-master` then your name will not be in the repo history. But I would like to have the recognition of your contribution. 

Your very current PR is against `master` so I am asking if you want to repoint it to `wix-v3-master`. If you don't have time for that I am happy to just do the change as in `wix-v4-master`.

**Comment by PatrickHofman** [comment]
> Sorry Patrick, I did not explain it well.
> 
> `master` branch is not used for PRs until WiX team completes the transition WiX3->WiX4. Then I will merge my `wix-v4-master` to `master` and close `wix-v3-master` forever.
> 
> But until this happens I have to duplicate all PRs with shared functionality in the two branches: `wix-v4-master` and `wix-v4-master`. (see [Code-Contributions-Guideline](https://github.com/oleg-shilo/wixsharp/wiki/Code-Contributions-Guideline))
> 
> I've repeated your change in `wix-v4-master` but if I do it in `wix-v3-master` then your name will not be in the repo history. But I would like to have the recognition of your contribution.
> 
> Your very current PR is against `master` so I am asking if you want to repoint it to `wix-v3-master`. If you don't have time for that I am happy to just do the change as in `wix-v4-master`.

I am sorry I missed your message. I am not sure how to repoint the pull request to v3. Do I need to edit that branch and then do a new pull request?

**Comment by oleg-shilo** [comment]
I do not think we can really repoint it. I would do it like this:

- Checkout (switch to) `wix-v3-master`  
- Make the change in `UIShell.cs` (it's simple as the change is not very extensive)
- Create PR to the remote origin

This is how I did it in `wix-v4-master`.

Thank you for coming back to me with this one

**Comment by oleg-shilo** [comment]
He Patrik, don't worry.

I have made the change on your behalf in the WiX3 branch. I just remembered that GitHub does not differentiate between Issues and PRs in terms of change management. And it also recognizes the contributors not via the merged PRs but via Release Notes (yep, it is a little weird). Thus I can achieve the objective of crediting your contribution by handling your change as a defect fix ([21ce39f](https://github.com/oleg-shilo/wixsharp/commit/21ce39f7981dc63d860de472d9f9796ff195b259)).

All done. You don't need to do anything. 
The change will be available in the very next release.

**Pull request closed without merging**
