### PR TITLE
Fix RemoveRegistryValue and RemoveRegistryKey

### PR DESCRIPTION
**Pull request by Xaddan**

### CODE REVIEW

**Comment by Xaddan** [comment]
I did not like the current implementation of adding features. All these checks are superfluous and duplicated. The `Map()` method must perform the necessary checks and create the necessary `Feature`, including `DefaultFeature`. We should only tell him which component to add to the function, and if the function is not specified, then DefaultFeature is automatically created.

But this is my opinion, it's up to you.

**Comment by oleg-shilo** [comment]
Of course. 

The `Map()` was internal and it was only ever called from `Compiler`. But now it is being called from every generic entity and I thought that you would end up adding the default implementation to one of the base classes.

Anyway I have added the default mapping implementation to `WixObject`. Please pull the changes and you can now do the mapping as below (the latest `RemoveRegistryValue` implementation):
```C#
public void Process(ProcessingContext context)
{
    XElement component = this.CreateParentComponent();
    component.Add(this.ToXElement("RemoveRegistryValue"));
    context.XParent.FindFirst("Component").Parent?.Add(component);

    base.MapComponentToFeatures(context, component.Attribute("Id").Value, ActualFeatures);
}
```

**Comment by Xaddan** [comment]
Why transfer `ActualFeatures` to `MapComponentToFeatures`? It is already in the base class.

**Comment by oleg-shilo** [comment]
Yeah I know you would ask that. I just don't like like ambiguous signatures: 
```C#
base.MapComponentToFeatures(component.Attribute("Id").Value, context);
```
It's not clear what features are. Some entities do not have components nor features even if there are members for them (e.g. `FileSearch`). Current signature is very clear. You know what component Id you are associating with what features. 

I would prefer to have `MapComponentToFeatures` with no dependency nor side affects. _You probably already sense that I am not a huge fun of OO and particularly inheritance (even if I use it)_. :)

`MapComponentToFeatures` is truly static by nature. I can even promote it to static. Will you be more comfortable with this?

```C#
public void Process(ProcessingContext context)
{
    XElement component = this.CreateParentComponent();
    component.Add(this.ToXElement("RemoveRegistryValue"));
    context.XParent.FindFirst("Component").Parent?.Add(component);

    MapComponentToFeatures(component.Attribute("Id").Value, ActualFeatures, context);
}
```

In this case it does not even need to be in `WixObject`. May be
```C#
    Tasks.MapComponentToFeatures(component.Attribute("Id").Value, ActualFeatures, context);
```

**Comment by Xaddan** [comment]
Yes, it is better to make it static. I thought you'd do it from the beginning. :)

**Comment by oleg-shilo** [comment]
Actually I did. Then I change my mind as I wanted to have `base.MapCom...`. :)
But... I agree, one cannot be both. It is either your static or instance. Will do it asap.

I will be going under radar for a while.  The Christmas is coming!

Marry Christmas and Happy New Year

**Comment by Xaddan** [comment]
I'm sorry i didn't quite understand if you've desided to leave it static or basic?

Happy holidays.

**Comment by oleg-shilo** [comment]
My bad, I meant I agree with you. "Static" is better.
It's don now.

**Comment by Xaddan** [comment]
I'm understood, thank you

**Pull request merged**
