### PR TITLE
Added file signing functionality to project build process

### PR DESCRIPTION
**Pull request by geghamyan**
Extends the file signing process by introducing `SignAllFiles` property in `WixSharp.Project`.
The less frequently used options have been moved to the SignAllFilesOptions class to improve code organization and maintainability.

### CODE REVIEW

**Comment by oleg-shilo** [comment]
Fantastic. Thank you Tigran.

Only one thing that I wanted to check with you.

Does it make sense to print a warning in the console if the user sets `project.SignAll` while the digital signature was not supplied? 
I have done it already for some other cases.

```C#
Compiler.OutputWriteLine($"WARNING: .....
```
And similarly, if users specify digital signature but `project.SignAll` is false, maybe it makes sense to show a warning like "not all files are going to be signed. consider setting `project.SignAll` to true".  
I do not mind encouraging signing all files.

And eventually, we can switch signAll to true by default. 

What do you think?

**Comment by oleg-shilo** [comment]
I will wait with wix-v4-master branch until your decision on this one

**Comment by geghamyan** [comment]
I agree with you on both cases. I will make changes to the PR according to your recommendation.

---
On completely unrelated note: when I checked out wix3 project, I have noticed that all projects target v4.6.2 framework, with the exception of `WixSharp.Samples/Wix# Samples/Bootstrapper/ManagedBA/ManagedBA.csproj`, which targets 4.6.1. Is this intentional?

**Comment by geghamyan** [comment]
One reason against setting `SignAllFiles` true by default - is the principle of avoiding side effects. If we consider the build project as a function where files are input parameters and the resulting installer is the output, setting `SignAllFiles` to true introduces a side effect by modifying the input files, which might not be immediately clear to the user. This makes the build process not-"pure" from a functional programming perspective.

**Comment by oleg-shilo** [comment]
>I will make changes to the PR according to your recommendation.

Great. Thank you

> ...which targets 4.6.1...   

Done. Txs

> ... reason against setting SignAllFiles true by default   

It's a valid point that I did not consider. 
If (or when) we want to go with the enabled by default we can simply make a copy of the file being signer signed (just next to the original file) and possibly call it `<original name>.signed.<original extension>`. And then include the signed copy instead of the original file.

**Comment by oleg-shilo** [comment]
All done, I just copied the warnings you created in wix4-master to wix3-master.

All your changes are now integrated.

I also added an extra note in the XML doc:

image

**Comment by oleg-shilo** [comment]
Will do the release in a day or two

**Comment by geghamyan** [comment]
Here are my thoughts on this:

- Now that I think about it, I believe it will be more practical if we sign the files intended for the installer. This will probably be what the developer expects and will simplify the whole process.

- Practicality over correctness - Though keeping the original files untouched and making signed copies makes sense theoretically, I think practicality should take precedence here. Most developers expect the signing process to integrate seamlessly into their existing workflow without unnecessary steps.

- Copying is expensive - creating copies of all to be signed can increase build times and consume resources. This might not be efficient, especially for larger projects.

- In most scenarios, the build pipeline will include a step for signing the files. These files are precisely the ones we will include in the installer, so I don't there is a reason to use them anywhere else in their unsigned form.

Given these points, I suggest we proceed with signing the files directly. This will likely be the preferred approach for most developers, simplifying the installer authoring process.

**Comment by oleg-shilo** [comment]
Not a problem. 
I can give you even one extra point to support your proposal. 
If the file is renamed it will appear in the progress dialog and the logs with a new name. The user will be puzzled about that. This can be avoided by keeping the original name but moving the copy into a different locatios. Then we are asking for trouble.

Anyway, All good. We only need to make `SignAllFiles = true;` by default and we are done. So let's have this and teh next release `SignAllFiles = false;`, Then `SignAllFiles = true;` with the warning in the release notes. So we enable the feature 
gradually. And I will point this out in the current release notes.

**Comment by geghamyan** [comment]
Let's make a choice that steers users to the more preferred direction, i.e. have all the files signed. In the release notes, please note that this is a significant (breaking?) change.
Worst case, if it turns out we missed some scenarios out of consideration, we can revert the change back to its original state.

**Comment by oleg-shilo** [comment]
OK
I usually do it with a comprehensive warning approach.
1. Release notes warning about coming change
2. Next Release warning about the chene delivered
3. Runtime warning when the new feature has been implicitly activated (e.g. `DigitalSignature` supplied but `SignAllFiles` is not touched).
4. Next-next Release runtime warning is removed.

**Pull request merged**
