### PR TITLE
Nsis bootstrapper

### PR DESCRIPTION
**Pull request by geghamyan**
EXE installers produced by NativeBootstrapper are vulnerable to DLL hijacking. Malicious code could potentially be loaded and executed by an installer.

I've added an alternative method to build a native bootstrapper through NsisBootstrapper class. It's drop-in replacement for NativeBootstrapper, and also supports the following additional capabilities:
* custom icon support
* version information
* UAC execution level

NSIS location is detected through environment variable WIXSHARP_NSISDIR or from regular installation path in %PROGRAMFILESX86%.

References:
* DLL Hijacking Just Won’t Die. https://textslashplain.com/2015/12/18/dll-hijacking-just-wont-die/
* Privilege escalation problems with NSIS installers. https://sourceforge.net/p/nsis/bugs/1125/
* NSIS DLL Hijack. https://packetstormsecurity.com/files/134693/NSIS-DLL-Hijack.html
* Secure loading of libraries to prevent DLL preloading attacks. https://support.microsoft.com/en-us/help/2389418/secure-loading-of-libraries-to-prevent-dll-preloading-attacks

### CODE REVIEW

**Comment by oleg-shilo** [comment]
Excellent contribution! I always felt about the existing native-bootstrapper as a lab exercise.
Thank you Tigran. 
Sorry but it will take some time for me to go through with the level of intention that is deserves.

**Comment by geghamyan** [comment]
Thank you Oleg ! Don't hesitate to let me know if any improvements or
changes are required.

**Comment by oleg-shilo** [comment]
After merging the PR I tested it... Worked like a charm. 
Will try to find some time to do the release on weekend.

I have also tested the _NativeBootstrapper_ for potential vulnerability to DLL hijacking as described in that "NSIS DLL Hijack" article. It successfully resisted dll injection/substitution. I attribute it to the fact that _NativeBootstrapper_ is statically linked and exhibits no dependency on any custom dll but only system libraries. 

I tried to substituting one of the system dll dependencies:  
image

Still the same result - the fake dll is ignored. Thus I am not sure _NativeBootstrapper_ is indeed "potentially vulnerable". But... it doesn't matter. I see a great value in your contribution as it delivers a proper high quality bootstrapping engine to the devs who are not happy with WiX/Burn. As for me it is already enough to make it to the main feature. 

Considering the value of the feature I am moving it to the primary solution instead of keeping in the "LAB" solution where _NativeBootstrapper_ is.

**Comment by geghamyan** [comment]
I assume you have tested the *NativeBootstrapper *on Windows 10 machine,
and luckily starting with Win10 the MS mitigated the security risks related
to the dll-preloading attack.
It's easily reproducible on Win7, Win8 (operating systems where .net
bootstrapping in general is more relevant) e.g. if you just put an empty
"version.dll" in the same folder as the setup executable.

One possible (but very realistic) attack vector on Win10 for
*NativeBootstrapper* might be when a malicious application monitors the
temporary folder for creation of Wix# directory (Temp\Wix#)  and
substitutes the extracted payload with a fake executable/msi. The Burn and
Nsis both mitigates the risk by randomizing the folder name each time.

Regards,
Tigran

**Comment by oleg-shilo** [comment]
Then even more reasons to enjoy Wix#-NSIS integration. thank you for such a comprehensive analysis.
And, yes I tested it on Win10.

**Comment by oleg-shilo** [comment]
Done. Released in v1.7.0

The feature currently described in this wiwki page: https://github.com/oleg-shilo/wixsharp/wiki/Wix%23-Bootstrapper-integration-notes

**Comment by oleg-shilo** [comment]
Hi Tigran, 

I have added you to the contributors thus if you ever feel the need describe you NsisBootstrapper then you can do it on WixSharp wiki: [NSIS Bootstrapper](NSISBootstrapper). I have granted you the edit rights.

I have already done it but only briefly (https://github.com/oleg-shilo/wixsharp/wiki/Wix%23-Bootstrapper-integration-notes).
I

**Comment by geghamyan** [comment]
Thank you, I will take a look once get back from a vacation.

**Pull request merged**
