### PR TITLE
Single Package Authoring

### PR DESCRIPTION
**Pull request by cloudlucky**
A InstallScopeDialog has been added.
It displays 2 radio buttons to be able to install per-user (MSIINSTALLPERUSER = 1) or per-machine (MSIINSTALLPERUSER = 0).

2 examples are provided to show how to use it.
The first one is a simple example to show the new InstallScopeDialog.
The second one shows how to keep the selection with registry when installing a new version of the application.

Related to: https://github.com/oleg-shilo/wixsharp/issues/166

### CODE REVIEW

**Comment by oleg-shilo** [comment]
I have adjusted the layout a little as it was distorted on my monitor (probably due to the scaling). Can you please have a look and test it in your environment to verify that the change did not create problems on your monitor. You can use master branch now.

Another question. I am tempted to move `e.Session["ALLUSERS"] = "2"` inside of the `InstallDirDialog_Load`. Did you consider when you implemented the dialog? Do you have any reasons to avoid setting ALLUSERS?

Thank you,
Oleg

**Comment by cloudlucky** [comment]
Hi Oleg,

It's still working but the display of the change directory button is a bit weird.
Here is what I see: 
image

OS: Windows 10
Resolution: 2560×1600
DPI: 227
Scaling: 150%

Yes, it can be a good idea to move `e.Session["ALLUSERS"] = "2"` inside of `InstallDirDialog_Load`
Note: I noticed that I forgot to rename `InstallDirDialog_Load` to `InstallScopeDialog_Load` in the `InstallScopeDialog`.

Also, I noticed that I forgot to change the path when it's a per-user install.
Right now, it's:
`MsiRuntime.Session[installDirProperty] = Environment.ExpandEnvironmentVariables($@"%LOCALAPPDATA%\Apps\My Company\My Product");`
but probably it should be 
`MsiRuntime.Session[installDirProperty] = Environment.ExpandEnvironmentVariables(@"%LOCALAPPDATA%\Apps\" + MsiRuntime.ProductName);`

Regards

**Comment by oleg-shilo** [comment]
Thank you, I have updated the code with your adjustments (envars, renaming and setting allusers ) and also realigned the "change" button. 

1600x900 150%
image

Can you please check it again as I don't have the screen that matches your aspect ratio.

Thank you,
Oleg

**Comment by cloudlucky** [comment]
Thank you Oleg, everything is perfect

**Comment by oleg-shilo** [comment]
Great. Your contribution will be available with the very next release.
Thank you.

**Pull request merged**
