### PR TITLE
Switched to the stock AdvSplash plugin

### PR DESCRIPTION
**Pull request by geghamyan**
Switched to the stock AdvSplash plugin
Added support to FadeIn, FadeOut, KeyColor parameters
https://nsis.sourceforge.io/Docs/AdvSplash/advsplash.txt

### CODE REVIEW

**Comment by oleg-shilo** [comment]
All good. Txs

**Comment by geghamyan** [comment]
Hi Oleg, do you want me do any improvement for this PR ?

**Comment by oleg-shilo** [comment]
> Hi Oleg, do you want me do any improvement for this PR ?

No. All good. I just forgot to press the "Merge" button :o)

I am ready to do the release. Though, I can delay it if you want to push more stuff.

**Comment by geghamyan** [comment]
Haha, please do the release, maybe I will find some time next week to contribute more. Thanks Oleg ! Keep up the good work with the project !

**Comment by oleg-shilo** [comment]
NP, I am in no rush. Take your time.

**Pull request merged**
