### PR TITLE
Add #error to custom UI template reminding people to replace the GUID

### PR DESCRIPTION
**Pull request by fredemmott**
There's a few google results for this GUID that probably shouldn't be using this GUID :)

I used `#error` based on line 5

### CODE REVIEW

**Comment by oleg-shilo** [comment]
Thank you Fred, 
Your change makes sense. I integrated it. I am closing this PR as the change needs to be done in the WiX4 branch `wix-v4-master`.
I also changed it to a warning instead of an error. And repeated your approach for all templates.

Thank you for your contribution.

**Comment by oleg-shilo** [comment]
Please note that at the moment I only released the nuget packages. The project template extension is yet to be released.

**Comment by nefarius** [comment]
I'm not too familiar with dotnet templates, is it possible to gebrate a new random GUID each time a new project is created from it?

**Comment by oleg-shilo** [comment]
> ... is it possible ...

Not exactly.

You can have something like this:
```C#
project.GUID = Guid.New();
```
Ore even not setting it at all.

But this will lead to a new GUID being generated every time you build your msi. Not a great experience :(

And VS does not offer any other templating mechanism.

**Comment by oleg-shilo** [comment]
Well... I am wrong. There is a mechanism :)
I do not know how I missed it: https://learn.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/eehb4faa(v=vs.100)?redirectedfrom=MSDN
Will do a quick template update release.

Thank you for insisting on this.

**Comment by oleg-shilo** [comment]
Done. 
VSTemplates v2.2.8
- added VS auto-generated project GUID ($guid1$)

**Pull request closed without merging**
