### PR TITLE
Detaching-signing-reattaching Burn engine

### PR DESCRIPTION
**Pull request by NJullienSweet**
This PR addresses the bundle signing issue mentioned in #1407 and #1289.

With WiX v4, the `insignia` has been removed and replaced with `wix burn`.
As described in the [WiX documentation](https://wixtoolset.org/docs/tools/signing/), these steps are needed to sign a bundle:
1. Build the bundle
2. Detach the Burn engine from the built bundle with `wix burn detach [options] original.exe -engine engine.exe`
4. Sign the Burn engine
5. Reattach the signed Burn engine with `wix burn reattach [options] original.exe -engine signed.exe -o final.exe`
6. Sign the whole bundle

What I did in this PR is adapt the code of the `DigitalySignBootstrapperEngine` static method in `CommonTasks.cs` by using `wix.exe` (if found) instead of `WixTools.SignTool` which was used here as a placeholder (according to https://github.com/oleg-shilo/wixsharp/issues/1289#issuecomment-1561017647)

I also added a `SigningBundle` sample to illustrate how to do and keep in line with WixSharp's teaching-by-example approach.

### CODE REVIEW

**Comment by oleg-shilo** [comment]
Hi Jullien, thank you for such a good quality PR. 
Merged.
Will go in the very next release (~this week).

**Comment by NJullienSweet** [comment]
Hey, same question here, was this released?

**Comment by oleg-shilo** [comment]
Yes, Nicolas, it has been released 4 days ago.
https://github.com/oleg-shilo/wixsharp/releases/tag/v2.0.5.0

I just added to the release notes a special acknowledgement section to credit you for the contribution. 
Thank you.

**Comment by NJullienSweet** [comment]
Haha I was not asking for a credit, but just pointed the fact that a "fixed" line was missing on the log. Anyway, thank you!

**Comment by oleg-shilo** [comment]
> Haha I was not asking for a credit.

You did not have too. 

You know that I have complimented your work even before it was merged. So it was only fair to give the credit when the credit was due.

But when I reviewed the release notes a few mins ago I discovered (to my embarrassment) that I had missed it and did not mention the PR. So I immediately fixed it :)

Interestingly enough GitHub extracts and prints the names of the contributors in the release page not based on the PR merged but on the names mentioned in release notes. Wired.

image

Even more reasons to update the release notes.

**Pull request merged**
