### PR TITLE
Added LaunchApplicationAction.

### PR DESCRIPTION
**Pull request by HavenDV**
Launches the application after the finish, if the corresponding checkbox is selected.

Usage:
```cs
new LaunchApplicationAction("EXE_ID")
{
    Description = "Launch app",
}
```

### CODE REVIEW

**Comment by oleg-shilo** [comment]
Great. Thank you.
All good. Can I ask you to update the `Wix# Samples\AllInOne\MyAppWix.cs` with `LaunchApplicationFromExitDialog("myapp_exe")` please.

We will also need to update the project validation routine so it emits the warning when `LaunchApplicationFromExitDialog` is used with ManagedUI. But I can do it when you address the PR comments.

**Comment by HavenDV** [comment]
Updated.

**Comment by oleg-shilo** [comment]
Great. Thank you

**Comment by oleg-shilo** [comment]
Hi Konstantin, 
Merry Christmas :)

I have a question. You have added the `new LaunchApplicationFromExitDialog(exeId: "myapp_exe", description: "Launch app"),` (e9d1818311c940526d3d0b6a1defdf738a1a1970). However it does prevent msi from being built for this sample. 

The reason is that in the sample the project defines native UI (`project.UI=...`) and yet the implementation expects the UI to be used:
https://github.com/oleg-shilo/wixsharp/blob/dc37457ced8f7b3c31544b4552d4352318386518/Source/src/WixSharp/LaunchApplicationFromExitDialog.cs#L65-L70

I placed a more informative exception there as a temp measure. Can you please review and probably rework the sample.

Thank you.

**Comment by HavenDV** [comment]
Hi Oleg.
I made this pull request according to this description:
https://wixtoolset.org/documentation/manual/v3/howtos/ui_and_localization/run_program_after_install.html

CustomUI is not needed for this to work. But I don't have enough knowledge about your project to make an implementation for the case where CustomUI = null.

According to the description, for the case without CustomUI, we need to include the following code inside the <UI> tag:
<UI>
  <UIRef Id="WixUI_Minimal" />
  <Publish Dialog="ExitDialog"
    Control="Finish" 
    Event="DoAction" 
    Value="LaunchApplication">WIXUI_EXITDIALOGOPTIONALCHECKBOX = 1 and NOT Installed</Publish>
</UI>

**Comment by oleg-shilo** [comment]
Thanks. I can take it from here.
This is how the solution looks now:
```C#
if (project.CustomUI == null)
{
    context.XParent.FindFirst("UI")
        .AddElement("Publish",
                    attributesDefinition:
                        "Dialog=ExitDialog;" +
                        "Control=Finish;" +
                        "Event=DoAction;" +
                        "Value=LaunchApplication",
                    value:
                        "WIXUI_EXITDIALOGOPTIONALCHECKBOX = 1 and NOT Installed");
}
else
{
    project.CustomUI
        .On(NativeDialogs.ExitDialog,
            Buttons.Finish,
            new ExecuteCustomAction(
                "LaunchApplication",
                "WIXUI_EXITDIALOGOPTIONALCHECKBOX = 1 and NOT Installed"));
}
```

**Pull request merged**
