### PR TITLE
Added missing namespace in custom dialog template

### PR DESCRIPTION
**Pull request by Bykiev**

### CODE REVIEW

**Comment by oleg-shilo** [comment]
Hi there,

Indeed the `using  WixSharpSetup` is missing. Thank you for pointing this out. Though by accident you have also submitted the change of uncommenting `DON'T FORGET to add NuGet package "WixSharp"`. Please revert this one and I will approve the PR.

Thank you

**Comment by Bykiev** [comment]
Hello @oleg-shilo,
It's my first PR, hope all is OK now. I've reverted all my changes and added missing namespace, but why does `DON'T FORGET to add NuGet package "WixSharp"` is not commented?

**Comment by oleg-shilo** [comment]
All good, thanks.

> but why does `DON'T FORGET to add NuGet package "WixSharp"` is not commented?

It needs to be uncommented in order to generate compiler error so the user know exactly why the solution does not build.

This, in turn, is required because the project template deliberately does not reference WixSharp NuGet package and requires user to add it explicitly.

This may change in the future but right now I don't want to include NuGet package for these reasons:
- Including it will prevent user from starting with the **latest** version of the package as the package referencing does not allow defining it as "version=max".
- Including it with "packages.config" will prevent user from changing it to "per-project" and vise versa.

None of these reasons is very strong and there is a good chance that it will change in the next releases. And then I will remove the comment completely.

**Comment by Bykiev** [comment]
Thank you for detailed explanation!

**Pull request merged**
